  name: MoarItems
  main: com.github.byrnorthil.moaritems.MoarItems
  version: 1.0-SNAPSHOT
  api-version: 1.16

  commands:
    giveglitterbomb:
      description: Gives a glitter bomb
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
    giveradar:
      description: Gives a radar
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>